modLoader="javafml"
loaderVersion="[40,)"
license="GNU GPLv3"

[[mods]]
modId="gunsowar"
#version="${file.jarVersion}"
version="0.0.2-1.18.2" # <-- I somehow fucked up here
displayName="Guns O' War"
logoFile="gunsowar.png"
credits="Code: Tornc; Art: Hailew, Laggyboi, Cell780; Balancing: Cell780"
authors="Tornc, Hailew, Laggyboi, Cell780"
description='''
Lots of code copied from MoGuns-Addon. see: https://github.com/Bomb787/MoGuns-Addon/tree/1.18.2
For any legal complaints, please contact Cell780 (@cell780) via discord.
'''
[[dependencies.gunsowar]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gunsowar]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gunsowar]]
    modId="cgm"
    mandatory=true
    versionRange="[1.2.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gunsowar]]
    modId="framework"
    mandatory=true
    versionRange="[0.2.3,)"
    ordering="NONE"
    side="BOTH"